 /**
 * app.js — NormalizerPro
 * Interactive features: SQL generator, replay mode,
 * FD live indicators, file upload parser, attribute
 * highlight, history (localStorage), theme toggle.
 * Depends on: algorithms.js + ui.js (must load first)
 */

function showPage(page) {
  // Get all page containers
  const pageHome  = document.getElementById('page-home');
  const pageTool  = document.getElementById('page-tool');
  const pageLearn = document.getElementById('page-learn');

  // Also handle non-wrapped tool content (hero + main + footer)
  const hero   = document.querySelector('.hero');
  const mainEl = document.querySelector('main');
  const footer = document.querySelector('footer');

  // Hide ALL pages first
  if (pageHome)  pageHome.style.display  = 'none';
  if (pageTool)  pageTool.style.display  = 'none';
  if (pageLearn) pageLearn.style.display = 'none';
  if (hero   && !pageTool) hero.style.display   = 'none';
  if (mainEl && !pageTool) mainEl.style.display  = 'none';
  if (footer && !pageTool) footer.style.display  = 'none';

  // Show the correct page
  if (page === 'home') {
    if (pageHome) pageHome.style.display = 'flex';
  } else if (page === 'learn') {
    if (pageLearn) pageLearn.style.display = 'block';
    else if (pageTool) pageTool.style.display = 'block';
  } else {
    // Tool page
    if (pageTool) {
      pageTool.style.display = 'block';
    } else {
      if (hero)   hero.style.display   = 'block';
      if (mainEl) mainEl.style.display = 'block';
      if (footer) footer.style.display = 'block';
    }
  }

  // ── UPDATE NAV TAB ACTIVE STATES ──────────────────────────
  // Remove active class from ALL nav buttons first
  const allNavBtns = document.querySelectorAll('.nav-tab');
  allNavBtns.forEach(btn => {
    btn.classList.remove('nav-tab-active');
    // Also reset inline styles that might override class
    btn.style.background    = '';
    btn.style.borderColor   = '';
    btn.style.color         = '';
  });

  // Add active class ONLY to the correct button
  const activeBtn = document.getElementById('nav-' + page);
  if (activeBtn) {
    activeBtn.classList.add('nav-tab-active');
  }
  // ──────────────────────────────────────────────────────────

  window.scrollTo({ top: 0, behavior: 'smooth' });
}

// ═══════════════════════════════════
//  UTILITIES
// ═══════════════════════════════════
const setEq=(a,b)=>a.size===b.size&&[...a].every(x=>b.has(x));
const setSubset=(a,b)=>[...a].every(x=>b.has(x));
const setUnion=(a,b)=>new Set([...a,...b]);
const strSet=s=>[...s].sort().join(',');

function generateSQL(){
  if(!_lastBCNF||!_lastBCNF.length){alert('Run normalization first.');return;}
  let sql='-- Generated by NormalizerPro\n-- BCNF Decomposition SQL\n\n';
  _lastBCNF.forEach((rel,i)=>{
    const keys=findCandidateKeys(rel.attrs,rel.fds);
    const pk=keys.length?keys[0]:[rel.attrs[0]];
    sql+=`CREATE TABLE ${rel.name} (\n`;
    rel.attrs.forEach(attr=>{
      const lower=attr.toLowerCase();
      let type='VARCHAR(100)';
      if(lower.includes('id'))type='INT';
      if(lower.includes('date')||lower.includes('time'))type='DATE';
      if(lower.includes('salary')||lower.includes('price')||lower.includes('fare'))type='DECIMAL(10,2)';
      if(lower.includes('qty')||lower.includes('quantity')||lower.includes('count'))type='INT';
      sql+=`  ${attr.padEnd(20)} ${type}`;
      if(pk.includes(attr))sql+='  NOT NULL';
      sql+=',\n';
    });
    sql+=`  PRIMARY KEY (${pk.join(', ')})`;
    _lastBCNF.forEach((other,j)=>{
      if(j===i)return;
      const oKeys=findCandidateKeys(other.attrs,other.fds);
      const oPK=oKeys.length?oKeys[0]:[other.attrs[0]];
      const shared=oPK.filter(a=>rel.attrs.includes(a)&&!pk.includes(a));
      if(shared.length===oPK.length&&shared.length>0)sql+=`,\n  FOREIGN KEY (${shared.join(', ')}) REFERENCES ${other.name}(${shared.join(', ')})`;
    });
    sql+='\n);\n\n';
  });
  document.getElementById('sql-output').textContent=sql;
  document.getElementById('sql-modal').style.display='flex';
}

function copySQL(){
  const sql=document.getElementById('sql-output').textContent;
  navigator.clipboard.writeText(sql).then(()=>{
    const btn=event.target;
    btn.textContent='✓ Copied!';
    setTimeout(()=>btn.textContent='⎘ Copy SQL',2000);
  });
}

// ═══════════════════
// REPLAY MODE
// ═══════════════════
const CARD_NARRATIONS={
  'card-parsed':'Step 1 of 10 — Input parsed. Schema and FDs loaded successfully.',
  'card-closure':'Step 2 of 10 — Closure Calculator ready. Select any attributes to compute their closure.',
  'card-keys':'Step 3 of 10 — Candidate Keys found. Prime and non-prime attributes classified.',
  'card-minimal':'Step 4 of 10 — Minimal Cover computed. Redundant FDs removed from the set.',
  'card-1nf':'Step 5 of 10 — 1NF confirmed. All attributes are atomic — no multi-valued groups.',
  'card-2nf':'Step 6 of 10 — 2NF applied. Partial dependencies removed by decomposition.',
  'card-3nf':'Step 7 of 10 — 3NF applied. Transitive dependencies eliminated.',
  'card-bcnf':'Step 8 of 10 — BCNF applied. Every FD left-hand side is now a superkey.',
  'card-lossless':'Step 9 of 10 — Properties verified. Lossless join and dependency preservation checked.',
  'card-summary':'Step 10 of 10 — Normalization complete! All normal forms achieved.',
};

function replayNormalization(){
  const allCards=[...document.querySelectorAll('#output-area .card')];
  if(!allCards.length){alert('Run normalization first, then click Replay.');return;}
  let bar=document.getElementById('replay-bar');
  if(!bar){
    bar=document.createElement('div');
    bar.id='replay-bar';
    bar.style.cssText=['position:fixed','bottom:1.5rem','left:50%','transform:translateX(-50%)','background:var(--bg2)','border:1px solid var(--teal)','border-radius:12px','padding:.85rem 1.75rem','font-family:var(--sans)','font-size:.875rem','color:var(--text)','z-index:9999','box-shadow:0 0 32px rgba(0,229,196,.25)','min-width:360px','max-width:600px','text-align:center','transition:opacity .3s','pointer-events:none'].join(';');
    document.body.appendChild(bar);
  }
  bar.style.opacity='1';
  const dots=allCards.map((_,i)=>`<span id="rdot-${i}" style="display:inline-block;width:8px;height:8px;border-radius:50%;background:var(--border);margin:0 3px;transition:background .3s;vertical-align:middle;"></span>`).join('');
  let currentIndex=0;
  function highlightCard(i){
    if(i>=allCards.length){
      bar.innerHTML=`<span style="color:var(--teal);font-weight:600;">✓ Replay complete!</span><div style="margin-top:.4rem">${dots.replace(/id="rdot-\d+"/g,m=>m)}</div>`;
      allCards.forEach((_,j)=>{const d=document.getElementById('rdot-'+j);if(d)d.style.background='var(--teal)';});
      setTimeout(()=>{bar.style.opacity='0';},2500);
      return;
    }
    const card=allCards[i];
    const cardId=card.id||'';
    let narration=`Step ${i+1} of ${allCards.length} — Processing...`;
    for(const[key,text]of Object.entries(CARD_NARRATIONS)){
      if(cardId.startsWith(key)||cardId===key){narration=text.replace(/Step \d+ of \d+/,`Step ${i+1} of ${allCards.length}`);break;}
    }
    allCards.forEach(c=>c.classList.remove('replay-active'));
    card.classList.add('replay-active');
    card.scrollIntoView({behavior:'smooth',block:'center'});
    const updatedDots=allCards.map((_,j)=>{
      let color=j<i?'var(--teal)':j===i?'var(--gold)':'var(--border)';
      return`<span style="display:inline-block;width:8px;height:8px;border-radius:50%;background:${color};margin:0 3px;vertical-align:middle;"></span>`;
    }).join('');
    bar.innerHTML=`<div style="font-size:.75rem;color:var(--text2);margin-bottom:.4rem;font-family:var(--mono);">REPLAY MODE</div><div style="color:var(--text);line-height:1.5;">${narration}</div><div style="margin-top:.6rem;">${updatedDots}</div>`;
    currentIndex=i+1;
    setTimeout(()=>{
      card.classList.remove('replay-active');
      setTimeout(()=>highlightCard(currentIndex),300);
    },1800);
  }
  document.getElementById('output-area').scrollIntoView({behavior:'smooth',block:'start'});
  setTimeout(()=>highlightCard(0),600);
}

// ═══════════════════
// FD SYNTAX HIGHLIGHTER
// ═══════════════════
function updateFDIndicators() {
  const textarea = document.getElementById('fd-input');
  const container = document.getElementById('fd-indicators');
  if (!container || !textarea) return;

  const schemaRaw = document.getElementById('schema-input').value.trim();
  const schema = schemaRaw ? parseSchema(schemaRaw) : null;
  const knownAttrs = schema ? new Set(schema.attrs) : null;

  const lines = textarea.value.split('\n');

  // Measure actual line height of textarea
  // Use computed style for accuracy
  const computed = window.getComputedStyle(textarea);
  const lineHeightPx = parseFloat(computed.lineHeight) || 22;
  const paddingTop = parseFloat(computed.paddingTop) || 12;

  container.innerHTML = '';
  container.style.paddingTop = paddingTop + 'px';

  lines.forEach((line) => {
    const dot = document.createElement('div');
    dot.style.cssText = `width: 7px; height: 7px; border-radius: 50%; margin-bottom: ${lineHeightPx - 7}px; margin-top: 0px; flex-shrink: 0;`;

    const trimmed = line.trim();

    if (!trimmed) {
      dot.style.background = 'transparent';
      dot.title = '';
    } else {
      const hasSep = trimmed.includes('->') || trimmed.includes('→');
      if (!hasSep) {
        dot.style.background = 'var(--red)';
        dot.style.boxShadow = '0 0 4px rgba(239,68,68,.5)';
        dot.title = 'Missing "->" separator';
      } else {
        const parsed = parseFDs(trimmed);
        const fd = parsed[0];
        if (!fd || !fd.lhs.length || !fd.rhs.length) {
          dot.style.background = 'var(--red)';
          dot.style.boxShadow = '0 0 4px rgba(239,68,68,.5)';
          dot.title = 'Invalid FD format';
        } else if (knownAttrs) {
          const unknowns = [...fd.lhs, ...fd.rhs].filter(a => !knownAttrs.has(a));
          if (unknowns.length) {
            dot.style.background = 'var(--gold)';
            dot.style.boxShadow = '0 0 4px rgba(245,158,11,.5)';
            dot.title = `Unknown attributes: ${unknowns.join(', ')}`;
          } else {
            dot.style.background = 'var(--green)';
            dot.style.boxShadow = '0 0 4px rgba(16,185,129,.4)';
            dot.title = 'Valid FD';
          }
        } else {
          dot.style.background = 'var(--teal)';
          dot.style.boxShadow = '0 0 4px rgba(0,229,196,.4)';
          dot.title = 'Valid syntax';
        }
      }
    }
    container.appendChild(dot);
  });
}

function handleFileUpload(event) {
  const file = event.target.files[0];
  if (!file) return;

  const allowedTypes = [
    'text/plain',
    'application/pdf',
    'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
    'application/msword',
  ];
  const allowedExts = ['.txt', '.pdf', '.docx', '.doc', '.text'];
  const ext = '.' + file.name.split('.').pop().toLowerCase();

  if (!allowedTypes.includes(file.type) && !allowedExts.includes(ext)) {
    showUploadStatus('error', `❌ Unsupported file type "${ext}". Please upload a .txt, .pdf, .docx, or .doc file.`);
    event.target.value = '';
    return;
  }

  showUploadStatus('loading', `⏳ Reading "${file.name}"...`);

  if (ext === '.txt' || file.type === 'text/plain') {
    const reader = new FileReader();
    reader.onload = (e) => processUploadedText(e.target.result, file.name);
    reader.onerror = () => showUploadStatus('error', '❌ Could not read file. Please try again.');
    reader.readAsText(file);
  } else if (ext === '.pdf') {
    const reader = new FileReader();
    reader.onload = (e) => {
      try {
        const bytes = new Uint8Array(e.target.result);
        let text = '';
        for (let i = 0; i < bytes.length; i++) {
          const b = bytes[i];
          if (b >= 32 && b <= 126) text += String.fromCharCode(b);
          else if (b === 10 || b === 13) text += '\n';
        }
        text = text.replace(/[^\x20-\x7E\n]/g, ' ').replace(/\s{3,}/g, '\n').trim();
        if (text.length < 20) {
          showUploadStatus('error', '❌ This PDF appears to be scanned/image-based and cannot be read as text. Please copy-paste the content manually.');
          return;
        }
        processUploadedText(text, file.name);
      } catch(err) {
        showUploadStatus('error', '❌ Could not read PDF. Please copy-paste the content manually.');
      }
    };
    reader.readAsArrayBuffer(file);
  } else if (ext === '.docx' || ext === '.doc') {
    const reader = new FileReader();
    reader.onload = (e) => {
      try {
        const bytes = new Uint8Array(e.target.result);
        let raw = '';
        for (let i = 0; i < bytes.length; i++) {
          raw += String.fromCharCode(bytes[i]);
        }
        const matches = raw.match(/<w:t[^>]*>([^<]+)<\/w:t>/g) || [];
        let text = matches.map(m => m.replace(/<[^>]+>/g, '')).join(' ');

        if (text.length < 20) {
          text = '';
          for (let i = 0; i < bytes.length; i++) {
            const b = bytes[i];
            if (b >= 32 && b <= 126) text += String.fromCharCode(b);
            else if (b === 10 || b === 13) text += '\n';
          }
          text = text.replace(/\s{3,}/g, '\n').trim();
        }

        if (text.length < 10) {
          showUploadStatus('error', '❌ Could not extract text from this Word document. Please copy-paste the content manually.');
          return;
        }
        processUploadedText(text, file.name);
      } catch(err) {
        showUploadStatus('error', '❌ Could not read Word document. Please copy-paste the content manually.');
      }
    };
    reader.readAsArrayBuffer(file);
  }

  event.target.value = '';
}

function processUploadedText(text, filename) {
  const schemaPatterns = [
    /([A-Za-z]\w*)\s*\(\s*([\w\s,]+)\s*\)/,           // R(A, B, C)
    /[Ss]chema\s*[:\-]?\s*([A-Za-z]\w*)\s*\(\s*([\w\s,]+)\s*\)/, // Schema: R(A,B,C)
    /[Rr]elation\s*[:\-]?\s*([A-Za-z]\w*)\s*\(\s*([\w\s,]+)\s*\)/, // Relation: R(...)
  ];

  let foundSchema = null;
  for (const pattern of schemaPatterns) {
    const m = text.match(pattern);
    if (m) {
      const attrs = m[2].split(',').map(a => a.trim()).filter(Boolean);
      if (attrs.length >= 2) {
        foundSchema = `${m[1]}(${attrs.join(', ')})`;
        break;
      }
    }
  }

  const fdPattern = /([A-Za-z]\w*(?:\s*,\s*[A-Za-z]\w*)*)\s*(?:->|→|=>|—>)\s*([A-Za-z]\w*(?:\s*,\s*[A-Za-z]\w*)*)/g;
  const fdLines = [];
  let match;
  while ((match = fdPattern.exec(text)) !== null) {
    const lhs = match[1].trim();
    const rhs = match[2].trim();
    if (lhs && rhs) {
      fdLines.push(`${lhs} -> ${rhs}`);
    }
  }

  if (!foundSchema && fdLines.length === 0) {
    showUploadStatus('error',
      `❌ Invalid input — no schema or functional dependencies found in "${filename}".<br>
       <span style="font-size:.78rem;">The file must contain a relation schema like <code>R(A, B, C)</code> and FDs like <code>A -> B</code>.</span>`
    );
    return;
  }

  if (!foundSchema && fdLines.length > 0) {
    showUploadStatus('warn',
      `⚠ FDs extracted (${fdLines.length} found) but no schema detected in "${filename}". Please enter the schema manually.`
    );
    document.getElementById('fd-input').value = fdLines.join('\n');
    updateFDIndicators();
    return;
  }

  if (foundSchema && fdLines.length === 0) {
    showUploadStatus('warn',
      `⚠ Schema extracted from "${filename}" but no FDs detected. Please enter FDs manually.`
    );
    document.getElementById('schema-input').value = foundSchema;
    updateFDIndicators();
    return;
  }

  document.getElementById('schema-input').value = foundSchema;
  document.getElementById('fd-input').value = fdLines.join('\n');
  updateFDIndicators();

  showUploadStatus('success',
    `✓ Extracted from "${filename}" — Schema: <strong>${foundSchema.split('(')[0]}</strong> with ${fdLines.length} FD${fdLines.length > 1 ? 's' : ''}. Review the fields below before running.`
  );
}

function showUploadStatus(type, message) {
  const el = document.getElementById('fd-upload-status');
  if (!el) return;

  const styles = {
    loading: 'background:rgba(100,116,139,.1);border:1px solid rgba(100,116,139,.3);color:var(--text2);',
    error:   'background:rgba(239,68,68,.1);border:1px solid rgba(239,68,68,.3);color:#fca5a5;',
    warn:    'background:rgba(245,158,11,.1);border:1px solid rgba(245,158,11,.3);color:#fcd34d;',
    success: 'background:rgba(0,229,196,.08);border:1px solid rgba(0,229,196,.2);color:var(--teal);',
  };

  el.style.cssText = `display: block; border-radius: 8px; font-size: .82rem; padding: .6rem .9rem; line-height: 1.5; ${styles[type] || styles.loading}`;
  el.innerHTML = message;

  if (type === 'success') {
    setTimeout(() => { el.style.display = 'none'; }, 6000);
  }
}

// ═══════════════════
// ATTRIBUTE HIGHLIGHT
// ═══════════════════
function highlightAttr(attrName){
  const all=document.querySelectorAll(`[data-attr="${attrName}"]`);
  all.forEach(el=>{
    el.classList.remove('attr-highlight');
    void el.offsetWidth;
    el.classList.add('attr-highlight');
    setTimeout(()=>el.classList.remove('attr-highlight'),2200);
  });
  document.querySelectorAll('.fd-pill').forEach(pill=>{
    if(pill.textContent.includes(attrName)){
      pill.style.transition='border-color .2s';
      pill.style.borderColor='var(--gold)';
      setTimeout(()=>pill.style.borderColor='',2200);
    }
  });
}

// ═══════════════════
// HISTORY
// ═══════════════════
const HISTORY_KEY='normPro_history';

function saveToHistory(schema,fdRaw){
  let history=JSON.parse(localStorage.getItem(HISTORY_KEY)||'[]');
  const entry={id:Date.now(),schema,fds:fdRaw,time:new Date().toLocaleString()};
  history=history.filter(h=>h.schema!==schema);
  history.unshift(entry);
  history=history.slice(0,5);
  localStorage.setItem(HISTORY_KEY,JSON.stringify(history));
  renderHistory();

  const list=document.getElementById('history-list');
  const arrow=document.getElementById('history-arrow');
  if(list&&list.style.display==='none'){
    list.style.display='flex';
    list.style.flexDirection='column';
    if(arrow)arrow.textContent='▾';
  }
}

function renderHistory(){
  const list = document.getElementById('history-list');
  if (!list) return;
  const history = JSON.parse(localStorage.getItem(HISTORY_KEY) || '[]');

  if (!history.length) {
    list.innerHTML = `<div style="display:flex;align-items:center;gap:.6rem;color:var(--text3);font-size:.82rem;font-style:italic;"><span style="font-size:1rem;">🕐</span>No history yet — run a normalization to save it here.</div>`;
    return;
  }

  list.innerHTML = `
    <div style="font-size:.72rem;color:var(--text3);text-transform:uppercase;letter-spacing:.07em;margin-bottom:.5rem;font-weight:600;">Last ${history.length} schema${history.length > 1 ? 's' : ''}</div>
    <div style="display:flex;flex-wrap:wrap;gap:.5rem;">
      ${history.map(h => {
        const name = h.schema.match(/^(\w+)\s*\(/)?.[1] || h.schema.substring(0, 18);
        const attrCount = (h.schema.match(/,/g) || []).length + 1;
        return `
          <div class="history-chip" title="Loaded at ${h.time} — Click to restore">
            <span onclick="loadFromHistory('${h.id}')" style="display:flex;align-items:center;gap:.4rem;">
              <span style="background:rgba(124,58,237,.15);color:var(--purple);border-radius:4px;font-size:.68rem;font-weight:700;padding:.1rem .4rem;">${attrCount} attrs</span>
              ${name}
            </span>
            <span class="del-btn" onclick="deleteHistory('${h.id}')" title="Remove from history">✕</span>
          </div>`;
      }).join('')}
    </div>`;
}

function loadFromHistory(id){
  const history=JSON.parse(localStorage.getItem(HISTORY_KEY)||'[]');
  const entry=history.find(h=>String(h.id)===String(id));
  if(!entry)return;
  document.getElementById('schema-input').value=entry.schema;
  document.getElementById('fd-input').value=entry.fds;
  updateFDIndicators();
}

function deleteHistory(id){
  let history=JSON.parse(localStorage.getItem(HISTORY_KEY)||'[]');
  history=history.filter(h=>String(h.id)!==String(id));
  localStorage.setItem(HISTORY_KEY,JSON.stringify(history));
  renderHistory();
}

function toggleHistory(){
  const list=document.getElementById('history-list');
  const arrow=document.getElementById('history-arrow');
  const isOpen=list.style.display!=='none';
  list.style.display=isOpen?'none':'flex';
  list.style.flexDirection='column';
  arrow.textContent=isOpen?'▸':'▾';
}

// ═══════════════════
// THEME TOGGLE
// ═══════════════════
function toggleTheme(){
  const body=document.body;
  body.classList.toggle('light-mode');
  const isLight=body.classList.contains('light-mode');
  document.getElementById('theme-icon').textContent=isLight?'☀️':'🌙';
  document.getElementById('theme-label').textContent=isLight?'Light':'Dark';
  localStorage.setItem('normPro_theme',isLight?'light':'dark');
}

window.addEventListener('DOMContentLoaded', () => {
  // Set correct initial nav state — home page shows first, so home tab is active
  const allNavBtns = document.querySelectorAll('.nav-tab');
  allNavBtns.forEach(btn => btn.classList.remove('nav-tab-active'));
  const homeBtn = document.getElementById('nav-home');
  if (homeBtn) homeBtn.classList.add('nav-tab-active');

  // Show home page, hide others
  const pageHome  = document.getElementById('page-home');
  const pageTool  = document.getElementById('page-tool');
  const pageLearn = document.getElementById('page-learn');
  if (pageHome)  pageHome.style.display  = 'flex';
  if (pageTool)  pageTool.style.display  = 'none';
  if (pageLearn) pageLearn.style.display = 'none';
  const hero      = document.querySelector('.hero');
  const mainEl    = document.querySelector('main');
  const footer    = document.querySelector('footer');
  if (hero && !pageTool)   hero.style.display   = 'none';
  if (mainEl && !pageTool) mainEl.style.display  = 'none';
  if (footer && !pageTool) footer.style.display  = 'none';

  // Other existing init code below (keep all of it):
  document.getElementById('schema-input').addEventListener('input', updateFDIndicators);
  renderHistory();
  if (localStorage.getItem('normPro_theme') === 'light') {
    document.body.classList.add('light-mode');
    const icon  = document.getElementById('theme-icon');
    const label = document.getElementById('theme-label');
    if (icon)  icon.textContent  = '☀️';
    if (label) label.textContent = 'Light';
  }

  // Smooth video background fade-in
  const bgVideo = document.getElementById('bg-video');
  if (bgVideo) {
    bgVideo.addEventListener('canplaythrough', () => {
      bgVideo.style.opacity = '1';
    });
    // Fallback: fade in after 1 second even if event doesn't fire
    setTimeout(() => {
      if (bgVideo) bgVideo.style.opacity = '1';
    }, 1000);

    // Handle autoplay policy on some browsers
    const playPromise = bgVideo.play();
    if (playPromise !== undefined) {
      playPromise.catch(() => {
        bgVideo.style.opacity = '0.7';
        console.log("Auto-play blocked by browser. Video will start on first click.");
        
        const startVideo = () => {
          bgVideo.play();
          bgVideo.style.opacity = '1';
          document.removeEventListener('click', startVideo);
          document.removeEventListener('touchstart', startVideo);
        };
        document.addEventListener('click', startVideo, { once: true });
        document.addEventListener('touchstart', startVideo, { once: true });
      });
    }

    // Remove audio track behavior — video is muted but ensure it stays that way
    bgVideo.muted = true;
    bgVideo.volume = 0;
  }
});
